
import "./globals.css";
import {Inter} from 'next/font/google'
import Navbar from "./Components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-b from-black to-slate-800`}>
        <Navbar/>
        {children}
        <footer className="flex justify-center p-4"><a href="https://porto.flax.vercel.app/" className="text-white text-center">© 2024 | Faizal Kamaludin</a></footer>
      </body>
    </html>
  );
}
